/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Usuario;

/**
 *
 * @author Denis Arango
 */
public class Inicio extends javax.swing.JFrame {

    Usuario mod;
    Inicio vInicio;
    Proveedores vProveedores;
    
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null); 
    }

    public Inicio(Usuario mod){
        initComponents();
        this.setLocationRelativeTo(null); 
        this.mod = mod;
        
        switch(mod.getIdRol()){
            case 1:
                break;
            case 2:
                opNuevaFactura.setVisible(false);
                menCompras.setVisible(false);
                break;
            case 3:
                menCompras.setVisible(false);
                menProveedores.setVisible(false);
                menUsuarios.setVisible(false);
                break;
            case 4:
                menFacturas.setVisible(false);
                menClientes.setVisible(false);
                menUsuarios.setVisible(false);
            break;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menFacturas = new javax.swing.JMenu();
        opNuevaFactura = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menProductos = new javax.swing.JMenu();
        opConsultarProductos = new javax.swing.JMenuItem();
        menClientes = new javax.swing.JMenu();
        opConsultarClientes = new javax.swing.JMenuItem();
        menCompras = new javax.swing.JMenu();
        opNuevoIngreso = new javax.swing.JMenuItem();
        menProveedores = new javax.swing.JMenu();
        opConsultarProveedores = new javax.swing.JMenuItem();
        menUsuarios = new javax.swing.JMenu();
        opConsultarUsuarios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menFacturas.setText("Facturas");

        opNuevaFactura.setText("Nueva Factura");
        menFacturas.add(opNuevaFactura);

        jMenuItem2.setText("Consultar Facturas");
        menFacturas.add(jMenuItem2);

        jMenuBar1.add(menFacturas);

        menProductos.setText("Productos");

        opConsultarProductos.setText("Consultar Productos");
        menProductos.add(opConsultarProductos);

        jMenuBar1.add(menProductos);

        menClientes.setText("Clientes");

        opConsultarClientes.setText("Consultar Clientes");
        opConsultarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opConsultarClientesActionPerformed(evt);
            }
        });
        menClientes.add(opConsultarClientes);

        jMenuBar1.add(menClientes);

        menCompras.setText("Compras");

        opNuevoIngreso.setText("Nuevo Ingreso");
        menCompras.add(opNuevoIngreso);

        jMenuBar1.add(menCompras);

        menProveedores.setText("Proveedores");

        opConsultarProveedores.setText("Proveedores");
        opConsultarProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opConsultarProveedoresActionPerformed(evt);
            }
        });
        menProveedores.add(opConsultarProveedores);

        jMenuBar1.add(menProveedores);

        menUsuarios.setText("Usuarios");

        opConsultarUsuarios.setText("Consultar Usuarios");
        menUsuarios.add(opConsultarUsuarios);

        jMenuBar1.add(menUsuarios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opConsultarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opConsultarClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opConsultarClientesActionPerformed

    private void opConsultarProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opConsultarProveedoresActionPerformed
        vProveedores = new Proveedores();
        vProveedores.setVisible(true);
    }//GEN-LAST:event_opConsultarProveedoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu menClientes;
    private javax.swing.JMenu menCompras;
    private javax.swing.JMenu menFacturas;
    private javax.swing.JMenu menProductos;
    private javax.swing.JMenu menProveedores;
    private javax.swing.JMenu menUsuarios;
    private javax.swing.JMenuItem opConsultarClientes;
    private javax.swing.JMenuItem opConsultarProductos;
    private javax.swing.JMenuItem opConsultarProveedores;
    private javax.swing.JMenuItem opConsultarUsuarios;
    private javax.swing.JMenuItem opNuevaFactura;
    private javax.swing.JMenuItem opNuevoIngreso;
    // End of variables declaration//GEN-END:variables
}
