/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Denis Arango
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        opConsultarFacturas = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        opConsultarProductos = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        opConsultarClientes = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        opNuevoIngreso = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        menProveedores = new javax.swing.JMenu();
        opNuevoProveedor = new javax.swing.JMenuItem();
        opConsultarProveedores = new javax.swing.JMenuItem();
        menDepartamentos = new javax.swing.JMenu();
        opNuevoDepartamento = new javax.swing.JMenuItem();
        opConsultarDepartamentos = new javax.swing.JMenuItem();
        menUsuarios = new javax.swing.JMenu();
        opNuevoUsuario = new javax.swing.JMenuItem();
        opConsultarUsuarios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        opConsultarFacturas.setText("Facturas");

        jMenuItem1.setText("Nueva Factura");
        opConsultarFacturas.add(jMenuItem1);

        jMenuItem2.setText("Consultar Facturas");
        opConsultarFacturas.add(jMenuItem2);

        jMenuBar1.add(opConsultarFacturas);

        opConsultarProductos.setText("Productos");

        jMenuItem3.setText("Consultar Productos");
        opConsultarProductos.add(jMenuItem3);

        jMenuBar1.add(opConsultarProductos);

        opConsultarClientes.setText("Clientes");

        jMenuItem4.setText("Nuevo Cliente");
        opConsultarClientes.add(jMenuItem4);

        jMenuItem5.setText("Consultar Clientes");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        opConsultarClientes.add(jMenuItem5);

        jMenuBar1.add(opConsultarClientes);

        opNuevoIngreso.setText("Compras");

        jMenuItem12.setText("Nuevo Ingreso");
        opNuevoIngreso.add(jMenuItem12);

        jMenuBar1.add(opNuevoIngreso);

        menProveedores.setText("Proveedores");

        opNuevoProveedor.setText("Nuevo Proveedor");
        menProveedores.add(opNuevoProveedor);

        opConsultarProveedores.setText("Consultar Proveedores");
        menProveedores.add(opConsultarProveedores);

        jMenuBar1.add(menProveedores);

        menDepartamentos.setText("Departamentos");

        opNuevoDepartamento.setText("Nuevo Departamento");
        menDepartamentos.add(opNuevoDepartamento);

        opConsultarDepartamentos.setText("Consultar Departamentos");
        menDepartamentos.add(opConsultarDepartamentos);

        jMenuBar1.add(menDepartamentos);

        menUsuarios.setText("Usuarios");

        opNuevoUsuario.setText("Nuevo Usuario");
        menUsuarios.add(opNuevoUsuario);

        opConsultarUsuarios.setText("Consultar Usuarios");
        menUsuarios.add(opConsultarUsuarios);

        jMenuBar1.add(menUsuarios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenu menDepartamentos;
    private javax.swing.JMenu menProveedores;
    private javax.swing.JMenu menUsuarios;
    private javax.swing.JMenu opConsultarClientes;
    private javax.swing.JMenuItem opConsultarDepartamentos;
    private javax.swing.JMenu opConsultarFacturas;
    private javax.swing.JMenu opConsultarProductos;
    private javax.swing.JMenuItem opConsultarProveedores;
    private javax.swing.JMenuItem opConsultarUsuarios;
    private javax.swing.JMenuItem opNuevoDepartamento;
    private javax.swing.JMenu opNuevoIngreso;
    private javax.swing.JMenuItem opNuevoProveedor;
    private javax.swing.JMenuItem opNuevoUsuario;
    // End of variables declaration//GEN-END:variables
}
